### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by spaceX-creater** [hpirila/ESP32-Arduino-SSH#1]
How u perform this steps:
- copy that file to the ESP32 SPIFFS file system
- copy the file back to server using different filename testFile2
i am try to send live captured audio data from esp32 to cloud server so i want to create ssh tunnel. i am beginner so can u help me regarding that?

**Comment by hpirila** [comment]
Hi

If you follow the instructions, the ESP32 will do those parts like copy the file to ESP32 and then back.

So the parts marked like this:

````do these parts````

You need to either modify main.cpp or execute in linux command line.

Regarding ssh tunnel, it is not supported. But yes, you should be able to copy audio data files from esp32 to cloud server using scpPut.

The instructions maybe not that clear and require improvement, I can help more if needed.

**Comment by spaceX-creater** [comment]
Hey

I'm attempting to construct a project where I capture audio from an esp32 and generate a local rtsp stream that plays the captured sound in real time. I then want to access the rtsp stream link to a cloud server without using port forwarding, a local device to forward the link, or a wifi router configuration.

After doing some research, I discovered that an ssh tunnel could be helpful in this situation. However, your library's functions are built for delivering files to cloud servers, not live data, so if you have any advice or ideas, please let me know.

Additionally, there's a chance that the ssh tunnel won't function with this method—I'm a novice in the networking world.

As you stated, "SSH tunnel is not supported. However, you should be able to use scpPut to copy audio data files from the esp32 to the cloud server." I'm not sure how to operate it.

Thanks

**Comment by hpirila** [comment]
Hi,

Your application looks quite complex for my skills too. I think it would push ESP32 into its limits also in computing and memory point of view. It could be easier to choose some more capable board like Raspberry Pi Zero 2 W. It supports ssh tunnel out of the box and I think your application would be easier to develop there.

**Comment by spaceX-creater** [comment]
Thanks for helping
